services:
  - type: web
    name: taskmanager-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project1.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    buildScript: ./render-build.sh
