services:
  - type: web
    name: your-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project1.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
