# Generated by Django 5.2.4 on 2025-07-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_todofolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.todofolder'),
        ),
    ]
