# Generated by Django 5.2.4 on 2025-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_todo_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todofolder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='todofolder',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todofolder',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
