# Generated by Django 5.2.4 on 2025-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_remove_todofolder_updated_at_todofolder_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
