# Generated by Django 5.2.4 on 2025-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_remove_todo_completed_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todofolder',
            name='user_folder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='todofolder',
            unique_together={('user', 'user_folder_id')},
        ),
    ]
