# Generated by Django 5.2.4 on 2025-08-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0009_todo_completed_todo_due_date_todo_priority_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='register_user_groups', related_query_name='register_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='register_user_permissions', related_query_name='register_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
